require 'json'

$BOX_IMAGE = "bento/ubuntu-22.04"
$CUSTOM_SCRIPT_DIR = "scripts/custom/"

parameters = JSON.parse(File.read("parameters.json"))

$NODE_COUNT_LAN = parameters["node_count_lan"] || 0
$LAN_SUBNET = parameters["lan_subnet"] || 0
$NODE_COUNT_DMZ = parameters["node_count_dmz"] || 0
$DUAL_FIREWALL = parameters["dual_firewall"] || 0
$F_LEARNING = 0
$BAD_CLIENT = 0
$SCRIPT_LIST_LAN = parameters["script_list_lan"] || ""
$SCRIPT_LIST_DMZ = parameters["script_list_dmz"] || ""
$SCRIPT_FIREWALL1 = parameters["script_firewall1"] || ""
$SCRIPT_FIREWALL2 = parameters["script_firewall2"] || ""
$SCRIPT_LANB = parameters["script_lanb"] || ""

Vagrant.configure("2") do |config|
    config.vm.boot_timeout = 900

    config.vm.provider "virtualbox" do |vb|
        vb.gui = true
    end

    if $F_LEARNING == 1
      load './learning.rb'
      configure_cluster(config)
    else
      load './dmz.rb'
      configure_cluster(config)
    end

end
  