require 'json'

$BOX_IMAGE = "bento/ubuntu-22.04"

parameters = JSON.parse(File.read("parameters.json"))

$NODE_COUNT_LAN = parameters["node_count_lan"] || 0
$LAN_SUBNET = parameters["lan_subnet"] || 0
$NODE_COUNT_DMZ = parameters["node_count_dmz"] || 0
$DUAL_FIREWALL = parameters["dual_firewall"] || 0
$F_LEARNING = 1

Vagrant.configure("2") do |config|
    config.vm.boot_timeout = 900

    config.vm.provider "virtualbox" do |vb|
        vb.gui = true
    end

    if $F_LEARNING == 1
      load './learning.rb'
      configure_cluster(config)
    else
      load './dmz.rb'
      configure_cluster(config)
    end

end
  